"""
Transaction code auto-generation (YYYY-MM-NNN) and insurance-only fields.
"""
from decimal import Decimal
from datetime import date

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool
from fastapi.testclient import TestClient

from app.models.models import (
    Base, Agent, Role, Client, Product, ProductType, OverrideRule,
)
from app.security import hash_password


@pytest.fixture
def client():
    engine = create_engine("sqlite://", connect_args={"check_same_thread": False},
                           poolclass=StaticPool)
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine, autoflush=False)
    s = Session()

    adm = Agent(code="ADM", name="Admin", email="adm@x.com", level=1, role=Role.ADMIN,
                password_hash=hash_password("pw"))
    ax = Agent(code="AX", name="AX", email="ax@x.com", level=1, role=Role.AGENT,
               password_hash=hash_password("pw"))
    s.add_all([adm, ax]); s.flush()
    ins = Product(code="INS", name="Whole Life", type=ProductType.INSURANCE,
                  base_commission_rate=Decimal("0.05"))
    fund = Product(code="FND", name="Fund", type=ProductType.FUND,
                   base_commission_rate=Decimal("0.01"))
    s.add_all([ins, fund])
    s.add(OverrideRule(product_type=ProductType.INSURANCE, level_gap=1,
                       override_rate=Decimal("0.25")))
    cx = Client(ref="CX", name="X", agent_id=ax.id)
    s.add(cx); s.commit()
    ids = {"ax": ax.id, "cx": cx.id, "ins": ins.id, "fund": fund.id}
    s.close()

    from app import main
    def override_get_db():
        db = Session()
        try:
            yield db
        finally:
            db.close()
    main.app.dependency_overrides[main.get_db] = override_get_db
    tc = TestClient(main.app)
    tc._ids = ids
    tc._Session = Session  # tests that need to inspect the DB directly
    yield tc
    main.app.dependency_overrides.clear()


def auth(tc, code="AX"):
    r = tc.post("/auth/login", json={"username": code, "password": "pw"})
    return {"Authorization": f"Bearer {r.json()['access_token']}"}


def _book(tc, h, ids, product_id, **extra):
    body = {"client_id": ids["cx"], "product_id": product_id, "agent_id": ids["ax"],
            "notional": "100000", "trade_date": "2026-08-15"}
    body.update(extra)
    return tc.post("/transactions", headers=h, json=body)


def test_ref_is_autogenerated_and_sequential(client):
    ids = client._ids
    h = auth(client, "ADM")  # only admin books transactions
    # preview endpoint agrees with the first assigned code
    nxt = client.get("/transactions/next-ref?period=2026-08", headers=h).json()
    assert nxt["ref"] == "2026-08-001"

    r1 = _book(client, h, ids, ids["fund"])
    r2 = _book(client, h, ids, ids["fund"])
    assert r1.json()["ref"] == "2026-08-001"
    assert r2.json()["ref"] == "2026-08-002"
    # a different month restarts the case counter
    r3 = _book(client, h, ids, ids["fund"], trade_date="2026-09-01")
    assert r3.json()["ref"] == "2026-09-001"


def test_insurance_details_live_on_product(client):
    """Insurance details are maintained on the product by an admin."""
    admin = auth(client, "ADM")
    r = client.post("/products", headers=admin, json={
        "code": "INS2", "name": "Term Plan", "type": "insurance",
        "base_commission_rate": "0.04",
        "payment_tenor": 20, "professional_investor": True,
        "age_min": 18, "age_max": 65,
        "year_commissions": ["0.30", "0.10", "0.05", "0", "0", "0", "0", "0", "0", "0"],
    })
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["payment_tenor"] == 20
    assert body["professional_investor"] is True
    assert body["age_min"] == 18 and body["age_max"] == 65
    assert body["year_commissions"][0] == "0.30" and len(body["year_commissions"]) == 10


def test_admin_maintains_insurance_details_via_patch(client):
    admin = auth(client, "ADM")
    # PATCH the seed-style insurance product's details.
    r = client.patch(f"/products/{client._ids['ins']}", headers=admin, json={
        "age_min": 5, "age_max": 75, "payment_tenor": 15,
        "year_commissions": ["0.35", "0.12"],
    })
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["age_min"] == 5 and body["age_max"] == 75 and body["payment_tenor"] == 15
    assert body["year_commissions"] == ["0.35", "0.12"]


def _direct_amount(client, txn_id):
    """Sum of the DIRECT commission amount for a transaction (from the ledger)."""
    from app.models.models import CommissionEntry, CommissionKind
    from sqlalchemy import select
    with client._Session() as s:
        rows = s.execute(select(CommissionEntry).where(
            CommissionEntry.transaction_id == txn_id,
            CommissionEntry.kind == CommissionKind.DIRECT)).scalars().all()
        return sum((e.amount for e in rows), __import__("decimal").Decimal("0")), rows


def test_rate_locked_at_creation(client):
    """A product-rate change after booking does NOT move the deal's commission."""
    admin = auth(client, "ADM")
    r = _book(client, admin, client._ids, client._ids["fund"])  # fund base rate 0.01
    assert r.status_code == 200, r.text
    tid = r.json()["id"]
    assert float(r.json()["locked_base_rate"]) == 0.01   # locked at creation
    client.post(f"/transactions/{tid}/approve", headers=admin)
    amt0, _ = _direct_amount(client, tid)
    assert amt0 == __import__("decimal").Decimal("1000.00")  # 100000 * 0.01

    # Admin raises the product rate to 5% AFTER the deal was booked, then recomputes.
    client.patch(f"/products/{client._ids['fund']}", headers=admin,
                 json={"base_commission_rate": "0.05"})
    client.post("/reports/recompute", headers=admin)
    amt1, _ = _direct_amount(client, tid)
    assert amt1 == __import__("decimal").Decimal("1000.00")  # unchanged — rate is locked


def test_rate_override_at_approval(client):
    """Admin can set the final rate at approval; the override sticks through recompute."""
    admin = auth(client, "ADM")
    tid = _book(client, admin, client._ids, client._ids["fund"]).json()["id"]
    # approve at 8% instead of the locked 1%
    r = client.post(f"/transactions/{tid}/approve", headers=admin,
                    json={"base_commission_rate": "0.08"})
    assert r.status_code == 200, r.text
    assert float(r.json()["locked_base_rate"]) == 0.08
    amt, rows = _direct_amount(client, tid)
    assert amt == __import__("decimal").Decimal("8000.00")  # 100000 * 0.08
    assert all(float(e.rate) == 0.08 for e in rows)
    # a later recompute keeps the override
    client.post("/reports/recompute", headers=admin)
    amt2, _ = _direct_amount(client, tid)
    assert amt2 == __import__("decimal").Decimal("8000.00")


def test_agent_transactions_review_list_is_enriched(client):
    """The agent review endpoint returns client/product names + the locked rate."""
    admin = auth(client, "ADM")
    ids = client._ids
    tid = _book(client, admin, ids, ids["fund"]).json()["id"]
    client.post(f"/transactions/{tid}/approve", headers=admin)
    # AX is the closing agent; fetch their own review list
    rows = client.get(f"/agents/{ids['ax']}/transactions", headers=auth(client, "AX")).json()
    row = next(r for r in rows if r["id"] == tid)
    assert row["client_name"] == "X"          # CX client name, resolved server-side
    assert row["product_name"] == "Fund"
    assert row["product_type"] == "fund"
    assert float(row["locked_base_rate"]) == 0.01  # locked at creation


def test_review_transactions_mine_scoped_and_enriched(client):
    """GET /transactions/mine returns the caller's own (closing) deals, enriched
    with client/product/agent names + the locked rate. An agent sees only their
    own (visible set == {self})."""
    admin = auth(client, "ADM")
    ids = client._ids
    tid = _book(client, admin, ids, ids["fund"]).json()["id"]
    client.post(f"/transactions/{tid}/approve", headers=admin)
    rows = client.get("/transactions/mine", headers=auth(client, "AX")).json()
    assert [r["id"] for r in rows] == [tid]          # only AX's own deal
    r = rows[0]
    assert r["agent_code"] == "AX" and r["client_name"] == "X" and r["product_name"] == "Fund"
    assert float(r["locked_base_rate"]) == 0.01


def test_review_transactions_include_lead_and_sales_dev_roles(client):
    """生意記錄 shows deals where the agent is lead/sales-dev, not only closer."""
    from app.models.models import Agent, Role
    from app.security import hash_password
    ids = client._ids
    # a second seller who will be the CLOSER
    with client._Session() as s:
        bx = Agent(code="BX", name="BX", email="bx@x.com", level=1, role=Role.AGENT,
                   password_hash=hash_password("pw"))
        s.add(bx); s.commit(); bx_id = bx.id
    admin = auth(client, "ADM")
    # BX closes; AX is the lead (AX did not close it)
    tid = _book(client, admin, ids, ids["fund"], agent_id=bx_id,
                lead_agent_id=ids["ax"], lead_pct="50", closing_pct="50").json()["id"]
    client.post(f"/transactions/{tid}/approve", headers=admin)
    # AX sees it in their review list even though BX is the closer
    rows = client.get("/transactions/mine", headers=auth(client, "AX")).json()
    row = next((r for r in rows if r["id"] == tid), None)
    assert row is not None                     # visible via the lead role
    assert row["agent_code"] == "BX"           # Agent column shows the closer
    # Lead / SDR / Closing role columns are resolved server-side
    assert row["lead_code"] == "AX" and float(row["lead_pct"]) == 50
    assert row["closing_code"] == "BX" and float(row["closing_pct"]) == 50
    assert row["sdr_code"] == "BX"             # sales-dev unset -> falls back to closer
    # ...and BX also sees it (as closer)
    assert any(r["id"] == tid for r in client.get("/transactions/mine", headers=auth(client, "BX")).json())


def test_client_code_autogenerated(client):
    """Creating a client without a ref auto-assigns C<YY><NNN>, sequentially."""
    import re
    from datetime import date
    ax = auth(client, "AX")
    aid = client._ids["ax"]
    yy = f"C{date.today().year % 100:02d}"
    preview = client.get("/clients/next-ref", headers=ax).json()["ref"]
    assert preview.startswith(yy)
    r1 = client.post("/clients", headers=ax, json={"name": "N1", "agent_id": aid})
    assert r1.status_code == 200, r1.text
    ref1 = r1.json()["ref"]
    assert re.fullmatch(rf"{yy}\d{{3,}}", ref1) and ref1 == preview
    r2 = client.post("/clients", headers=ax, json={"name": "N2", "agent_id": aid})
    ref2 = r2.json()["ref"]
    assert int(ref2[len(yy):]) == int(ref1[len(yy):]) + 1     # sequential
    # an explicit ref is still honoured
    r3 = client.post("/clients", headers=ax, json={"ref": "VIP-1", "name": "N3", "agent_id": aid})
    assert r3.json()["ref"] == "VIP-1"


def test_only_admin_maintains_products(client):
    agent = auth(client, "AX")
    # non-admin cannot create or patch products
    assert client.post("/products", headers=agent, json={
        "code": "X", "name": "x", "type": "insurance", "base_commission_rate": "0.05",
    }).status_code == 403
    assert client.patch(f"/products/{client._ids['ins']}", headers=agent,
                        json={"age_min": 1}).status_code == 403


def test_insurance_base_rate_follows_yr1(client):
    admin = auth(client, "ADM")
    # base_commission_rate is overridden to the Yr1 commission for insurance.
    r = client.post("/products", headers=admin, json={
        "code": "INSY", "name": "Y", "type": "insurance", "base_commission_rate": "0.99",
        "year_commissions": ["0.20", "0.05", "0", "0", "0", "0", "0", "0", "0", "0"],
    })
    assert r.status_code == 200, r.text
    pid = r.json()["id"]
    assert float(r.json()["base_commission_rate"]) == 0.20  # = Yr1, not 0.99
    # editing Yr1 moves the base rate with it
    r2 = client.patch(f"/products/{pid}", headers=admin,
                      json={"year_commissions": ["0.15", "0.05"]})
    assert float(r2.json()["base_commission_rate"]) == 0.15


def test_delete_product_admin_only_and_unused(client):
    admin = auth(client, "ADM")
    agent = auth(client, "AX")
    pid = client.post("/products", headers=admin, json={
        "code": "DEL", "name": "d", "type": "fund", "base_commission_rate": "0.01",
    }).json()["id"]
    # non-admin cannot delete
    assert client.delete(f"/products/{pid}", headers=agent).status_code == 403
    # admin can delete an unused product
    assert client.delete(f"/products/{pid}", headers=admin).status_code == 200
    assert all(p["code"] != "DEL" for p in client.get("/products", headers=agent).json())


def test_delete_product_removes_per_company_rates(client):
    """Deleting a product must also drop its ProductRate rows — otherwise they
    orphan and a later product reusing the id collides / inherits stale rates."""
    from app.models.models import ProductRate
    admin = auth(client, "ADM")
    pid = client.post("/products", headers=admin, json={
        "code": "DELR", "name": "d", "type": "insurance",
        "base_commission_rate": "0.05", "year_commissions": ["0.05", "0.01"],
    }).json()["id"]
    with client._Session() as s:
        assert s.query(ProductRate).filter_by(product_id=pid).count() == 2  # heritree + cpm
    assert client.delete(f"/products/{pid}", headers=admin).status_code == 200
    with client._Session() as s:
        assert s.query(ProductRate).filter_by(product_id=pid).count() == 0


def test_delete_product_blocked_when_in_use(client):
    ids = client._ids
    admin = auth(client, "ADM")
    _book(client, admin, ids, ids["fund"])  # a transaction now references the fund
    assert client.delete(f"/products/{ids['fund']}", headers=admin).status_code == 409


def test_admin_updates_and_deletes_override_rule(client):
    admin = auth(client, "ADM")
    agent = auth(client, "AX")
    rid = client.get("/override-rules", headers=admin).json()[0]["id"]
    # update the rate
    r = client.patch(f"/override-rules/{rid}", headers=admin, json={"override_rate": "0.30"})
    assert r.status_code == 200 and float(r.json()["override_rate"]) == 0.30
    # non-admin is forbidden to update or delete
    assert client.patch(f"/override-rules/{rid}", headers=agent,
                        json={"override_rate": "0.1"}).status_code == 403
    assert client.delete(f"/override-rules/{rid}", headers=agent).status_code == 403
    # admin deletes it
    assert client.delete(f"/override-rules/{rid}", headers=admin).status_code == 200
    assert all(x["id"] != rid for x in client.get("/override-rules", headers=admin).json())
