"""
Transaction code auto-generation (YYYY-MM-NNN) and insurance-only fields.
"""
from decimal import Decimal
from datetime import date

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool
from fastapi.testclient import TestClient

from app.models.models import (
    Base, Agent, Role, Client, Product, ProductType, OverrideRule,
)
from app.security import hash_password


@pytest.fixture
def client():
    engine = create_engine("sqlite://", connect_args={"check_same_thread": False},
                           poolclass=StaticPool)
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine, autoflush=False)
    s = Session()

    adm = Agent(code="ADM", name="Admin", email="adm@x.com", level=1, role=Role.ADMIN,
                password_hash=hash_password("pw"))
    ax = Agent(code="AX", name="AX", email="ax@x.com", level=1, role=Role.AGENT,
               password_hash=hash_password("pw"))
    s.add_all([adm, ax]); s.flush()
    ins = Product(code="INS", name="Whole Life", type=ProductType.INSURANCE,
                  base_commission_rate=Decimal("0.05"))
    fund = Product(code="FND", name="Fund", type=ProductType.FUND,
                   base_commission_rate=Decimal("0.01"))
    s.add_all([ins, fund])
    s.add(OverrideRule(product_type=ProductType.INSURANCE, level_gap=1,
                       override_rate=Decimal("0.25")))
    cx = Client(ref="CX", name="X", agent_id=ax.id)
    s.add(cx); s.commit()
    ids = {"ax": ax.id, "cx": cx.id, "ins": ins.id, "fund": fund.id}
    s.close()

    from app import main
    def override_get_db():
        db = Session()
        try:
            yield db
        finally:
            db.close()
    main.app.dependency_overrides[main.get_db] = override_get_db
    tc = TestClient(main.app)
    tc._ids = ids
    yield tc
    main.app.dependency_overrides.clear()


def auth(tc, code="AX"):
    r = tc.post("/auth/login", json={"username": code, "password": "pw"})
    return {"Authorization": f"Bearer {r.json()['access_token']}"}


def _book(tc, h, ids, product_id, **extra):
    body = {"client_id": ids["cx"], "product_id": product_id, "agent_id": ids["ax"],
            "notional": "100000", "trade_date": "2026-08-15"}
    body.update(extra)
    return tc.post("/transactions", headers=h, json=body)


def test_ref_is_autogenerated_and_sequential(client):
    ids = client._ids
    h = auth(client)
    # preview endpoint agrees with the first assigned code
    nxt = client.get("/transactions/next-ref?period=2026-08", headers=h).json()
    assert nxt["ref"] == "2026-08-001"

    r1 = _book(client, h, ids, ids["fund"])
    r2 = _book(client, h, ids, ids["fund"])
    assert r1.json()["ref"] == "2026-08-001"
    assert r2.json()["ref"] == "2026-08-002"
    # a different month restarts the case counter
    r3 = _book(client, h, ids, ids["fund"], trade_date="2026-09-01")
    assert r3.json()["ref"] == "2026-09-001"


def test_insurance_details_live_on_product(client):
    """Insurance details are maintained on the product by an admin."""
    admin = auth(client, "ADM")
    r = client.post("/products", headers=admin, json={
        "code": "INS2", "name": "Term Plan", "type": "insurance",
        "base_commission_rate": "0.04",
        "payment_tenor": 20, "professional_investor": True,
        "age_min": 18, "age_max": 65,
        "year_commissions": ["0.30", "0.10", "0.05", "0", "0", "0", "0", "0", "0", "0"],
    })
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["payment_tenor"] == 20
    assert body["professional_investor"] is True
    assert body["age_min"] == 18 and body["age_max"] == 65
    assert body["year_commissions"][0] == "0.30" and len(body["year_commissions"]) == 10


def test_admin_maintains_insurance_details_via_patch(client):
    admin = auth(client, "ADM")
    # PATCH the seed-style insurance product's details.
    r = client.patch(f"/products/{client._ids['ins']}", headers=admin, json={
        "age_min": 5, "age_max": 75, "payment_tenor": 15,
        "year_commissions": ["0.35", "0.12"],
    })
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["age_min"] == 5 and body["age_max"] == 75 and body["payment_tenor"] == 15
    assert body["year_commissions"] == ["0.35", "0.12"]


def test_only_admin_maintains_products(client):
    agent = auth(client, "AX")
    # non-admin cannot create or patch products
    assert client.post("/products", headers=agent, json={
        "code": "X", "name": "x", "type": "insurance", "base_commission_rate": "0.05",
    }).status_code == 403
    assert client.patch(f"/products/{client._ids['ins']}", headers=agent,
                        json={"age_min": 1}).status_code == 403
